- name: copying mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb-org package
  ansible.builtin.dnf:
      name: mongodb-org
      state: present

- name: start and enable systemctl service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true

- name: open to remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: "restart services"
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: true