- name: app set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: systemd set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml



- name: "starting and enabling {{ component }} service"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: true
