
  - name: Enabling nginx:1.24 version
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
    
  - name: Remove old nginx html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Recreate nginx html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
      owner: nginx
      group: nginx
      mode: '0755'


  - name: downloading frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip downloaded code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: copying ngix conf
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

