- name: app set-up
  tags:
  - deployment # you can call ansible-playbook -e component=catalogue -t deployment roboshop.yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: systemd set-up
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml


- name: copying mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded
  ansible.builtin.command: mongosh --host "{{ mongodb_host }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print the output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load the products
  ansible.builtin.shell: mongosh --host "{{ mongodb_host }}" </app/db/master-data.js
  when: catalogue_output.stdout  | int < 0

- name: restart service
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: true