  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      system: true
      comment: roboshop system user
      home: /app
      shell: /sbin/nologin

  - name: Deleting app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: Creating directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete default {{ component }} zip code
    ansible.builtin.file:
       path: /tmp/{{ component }}.zip
       state: absent

  - name: Downloading {{ component }} code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
      dest: /tmp/{{ component }}.zip

  - name: unzip {{ component }} code
    ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes
