- name: Enabling nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install dependencies
  community.general.npm:
      path: /app


